--- #YAML:1.0
name:                HeliosX-MetajobService
version:             0.02_0771
abstract:            Alternative Helios::Service class to provide simple map/reduce operations
license:             perl
author:              
    - Andrew Johnson <lajandy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Helios:                        2
    HeliosX::ExtLoggerService:     0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
